table 'Housing Data'
	lineageTag: 3a78dd3b-f812-4670-b6d7-ab0801ddc09e

	column date
		dataType: dateTime
		formatString: Long Date
		lineageTag: fa287ab6-8f9a-499e-bdf4-684b5ecf7335
		summarizeBy: none
		sourceColumn: date

		variation Variation
			isDefault
			relationship: 5b53250b-386f-4eb3-aef8-012e902b5bae
			defaultHierarchy: LocalDateTable_f650ae6e-46dd-4672-a4f8-673d4f9954c1.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column quarter
		dataType: string
		lineageTag: 409b46bf-6797-4bcf-a466-d37385cf0333
		summarizeBy: none
		sourceColumn: quarter

		annotation SummarizationSetBy = Automatic

	column house_id
		dataType: int64
		formatString: 0
		lineageTag: 63b77518-19d2-4b6b-bc50-7dabb9f7be33
		summarizeBy: sum
		sourceColumn: house_id

		annotation SummarizationSetBy = Automatic

	column house_type
		dataType: string
		lineageTag: 70fd1feb-5eae-4e3c-b2a6-a3ad6233466a
		summarizeBy: none
		sourceColumn: house_type

		annotation SummarizationSetBy = Automatic

	column sales_type
		dataType: string
		lineageTag: 5555f878-9736-4942-a90b-0eff0565d6dc
		summarizeBy: none
		sourceColumn: sales_type

		annotation SummarizationSetBy = Automatic

	column year_build
		dataType: int64
		formatString: 0
		lineageTag: 18482790-7ee5-4c65-82e2-5874ef26398b
		summarizeBy: sum
		sourceColumn: year_build

		annotation SummarizationSetBy = Automatic

	column purchase_price
		dataType: int64
		formatString: 0
		lineageTag: d7bf70c1-778c-4e5c-8319-79511ab2de91
		summarizeBy: sum
		sourceColumn: purchase_price

		annotation SummarizationSetBy = Automatic

	column %_change_between_offer_and_purchase
		dataType: int64
		formatString: 0
		lineageTag: 1800f429-62ec-49d1-adf1-a8a86831fd53
		summarizeBy: sum
		sourceColumn: %_change_between_offer_and_purchase

		annotation SummarizationSetBy = Automatic

	column no_rooms
		dataType: int64
		formatString: 0
		lineageTag: f54b2644-a9e6-44e0-818f-65e39996aa72
		summarizeBy: sum
		sourceColumn: no_rooms

		annotation SummarizationSetBy = Automatic

	column sqm
		dataType: int64
		formatString: 0
		lineageTag: a2739972-89b2-47b8-9812-0ab5f4014e1a
		summarizeBy: sum
		sourceColumn: sqm

		annotation SummarizationSetBy = Automatic

	column sqm_price
		dataType: double
		lineageTag: adad9c13-2f3c-4436-bc20-1742f32d983d
		summarizeBy: sum
		sourceColumn: sqm_price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column address
		dataType: string
		lineageTag: 3fa24eda-7b5a-4185-9a80-7ff2bbefb93d
		summarizeBy: none
		sourceColumn: address

		annotation SummarizationSetBy = Automatic

	column zip_code
		dataType: int64
		formatString: 0
		lineageTag: 75d6741e-720e-46f9-89a0-503aaa8b5df7
		summarizeBy: sum
		sourceColumn: zip_code

		annotation SummarizationSetBy = Automatic

	column city
		dataType: string
		lineageTag: e9099b45-f7f2-4e5f-8d41-0d6488d5b37c
		summarizeBy: none
		sourceColumn: city

		annotation SummarizationSetBy = Automatic

	column area
		dataType: string
		lineageTag: 0d6aca45-3cd4-4b2a-b4b4-2c358466bb5d
		summarizeBy: none
		sourceColumn: area

		annotation SummarizationSetBy = Automatic

	column region
		dataType: string
		lineageTag: b72b8dbd-e00b-4509-95ab-1c01a955a50f
		summarizeBy: none
		sourceColumn: region

		annotation SummarizationSetBy = Automatic

	column nom_interest_rate%
		dataType: double
		lineageTag: 4e4295c6-dcc8-4a22-a8cb-4821da7fea67
		summarizeBy: sum
		sourceColumn: nom_interest_rate%

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column dk_ann_infl_rate%
		dataType: double
		lineageTag: b95d849a-11c4-4604-ad61-89b882c46c4c
		summarizeBy: sum
		sourceColumn: dk_ann_infl_rate%

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column yield_on_mortgage_credit_bonds%
		dataType: double
		lineageTag: b94b9087-47bf-4502-b9e7-c5d1f388d58a
		summarizeBy: sum
		sourceColumn: yield_on_mortgage_credit_bonds%

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Offer Price' = 100* 'Housing Data'[purchase_price]/(100- 'Housing Data'[%_change_between_offer_and_purchase])
		lineageTag: d6d9edb7-702f-4e2c-970f-24a1a494c89b
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Age = ABS(YEAR('Housing Data'[date].[Date])-'Housing Data'[year_build])
		formatString: 0
		lineageTag: dba0216c-0bf7-477e-859a-161db3d66120
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition 'Housing Data' = m
		mode: import
		source =
				let
				    Source = GoogleBigQuery.Database([Implementation="2.0"]),
				    #"housing-502508_Database" = Source{[Name="housing-502508",Kind="Database"]}[Data],
				    #"1_Schema" = #"housing-502508_Database"{[Name="1",Kind="Schema"]}[Data],
				    Housing_Table = #"1_Schema"{[Name="Housing",Kind="Table"]}[Data],
				    #"Replaced Value" = Table.ReplaceValue(Housing_Table,null,1.85,Replacer.ReplaceValue,{"dk_ann_infl_rate%"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value",null,1.47,Replacer.ReplaceValue,{"yield_on_mortgage_credit_bonds%"})
				in
				    #"Replaced Value1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

