table 'Measure Table 1'
	lineageTag: b63e3afb-50ed-42cb-af77-832c8f885c98

	measure 'Last 12 Month Sales' =
			
			CALCULATE(
			    SUM('Housing Data'[purchase_price]),
			    DATESINPERIOD(
			        'Housing Data'[date],
			        MAX('Housing Data'[date]),
			        -12,
			        MONTH
			    )
			)
		formatString: 0
		lineageTag: ab1ad6b9-93cf-4bf4-a0e2-fe2b2ac63c1d

	measure 'Median Sales Price Change' = ```
			
			Var CurrMedianPrice = 
			        MEDIANX(FILTER('Housing Data',YEAR('Housing Data'[date].[Date]) = YEAR(MAX('Housing Data'[date].[Date]))), 'Housing Data'[purchase_price])
			
			Var PreMedianPrice =
			        MEDIANX(FILTER('Housing Data',YEAR('Housing Data'[date]) = YEAR(MAX('Housing Data'[date].[Date]))-1),'Housing Data'[purchase_price])
			
			    RETURN
			         IF(PreMedianPrice<>0, (CurrMedianPrice-PreMedianPrice)/PreMedianPrice, BLANK())
			```
		lineageTag: 65fcaa40-14ac-46e2-8e8d-5c3be1355b4e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Units Sold in Latest Year and Quarter' = CALCULATE(DISTINCTCOUNT('Housing Data'[house_id]), YEAR('Housing Data'[date]) = YEAR(MAX('Housing Data'[date])) && QUARTER('Housing Data'[date]) = QUARTER(MAX('Housing Data'[date])))
		formatString: 0
		lineageTag: cfde6cc6-77e6-4ae6-b235-668deb00f4da

	measure YOY_Sales_Growth = ```
			
			Var CurrYearSales = 
			    CALCULATE(SUM('Housing Data' [purchase_price]),
			              YEAR('Housing Data'[date]) = YEAR(MAX('Housing Data'[date])))
			
			Var Preyearsales =
			    CALCULATE(SUM('Housing Data' [purchase_price]),
			              YEAR('Housing Data'[date]) = YEAR(MAX('Housing Data'[date]))-1)
			
			Return
			     IF(Preyearsales<>0, (CurrYearSales-Preyearsales)/Preyearsales, BLANK())
			
			```
		lineageTag: 0bc9a007-3986-4ea1-b5c6-87bc2cac7bd3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Sales by Region' = CALCULATE(SUM('Housing Data'[purchase_price]), ALLEXCEPT('Housing Data','Housing Data'[region]))
		formatString: 0
		lineageTag: c5d931f7-9089-4560-9873-e0095f30ed72

	measure 'Total YTD' = TOTALYTD(SUM('Housing Data'[purchase_price]), 'Housing Data'[date].[Date])
		formatString: 0
		lineageTag: 43656a12-2c9d-47ed-92b7-03920114d2aa

	measure 'Average Price SQM' = AVERAGE('Housing Data'[sqm_price])
		lineageTag: 2a278eab-7017-4990-8869-04e9d96da38d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Offer to SQM Ratio' = DIVIDE(SUM('Housing Data'[Offer Price]), SUM('Housing Data'[sqm]))
		lineageTag: dea13bac-5dff-4ddb-b030-36f586de425f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Measure Table 1' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

